services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skarmdump-backend
    ports:
      - "8085:8080"
    env_file:
      - .env
    volumes:
      - ./img:/app/img
    restart: unless-stopped
